# Generated by Django 4.2.11 on 2024-04-10 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('admin_honeypot', '0002_auto_20160208_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginattempt',
            name='session_key',
            field=models.CharField(blank=True, max_length=255, null=True,
                                   verbose_name='session key'),
        ),
    ]
